<a href="https://colab.research.google.com/github/amirmuktar369/Data-Analysis/blob/main/Data%20Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing necessary libraries

In [78]:
import pandas as pd
import numpy as np

Loading the dataset and checking it's dimensions

In [79]:
df = pd.read_csv("/Business Funding Data.csv", encoding='latin-1')
df.head()

,Website Domain,Effective date,Found At,Financing Type,Financing Type Normalized,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,NaN,2024-03-14T01:00:00+01:00,NaN,NaN,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,NaN,2024-05-31T02:00:00+02:00,NaN,NaN,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,NaN,2024-07-24T02:00:00+02:00,NaN,NaN,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,NaN,2024-05-01T02:00:00+02:00,NaN,NaN,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,NaN,2024-04-11T02:00:00+02:00,NaN,NaN,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...

In [80]:
df.shape

(26, 11)

Getting the general information of the dataset

In [81]:
df.info

<bound method DataFrame.info of          Website Domain             Effective date                   Found At  \
0         trafigura.com                        NaN  2024-03-14T01:00:00+01:00
1            zenobe.com                        NaN  2024-05-31T02:00:00+02:00
2            zenobe.com                        NaN  2024-07-24T02:00:00+02:00
3             canva.com                        NaN  2024-05-01T02:00:00+02:00
4          fidelity.com                        NaN  2024-04-11T02:00:00+02:00
5       swtchenergy.com  2024-04-18T02:00:00+02:00  2024-04-24T02:00:00+02:00
6            carnow.com  2024-04-16T02:00:00+02:00  2024-04-16T02:00:00+02:00
7        databricks.com                        NaN  2024-08-07T02:00:00+02:00
8         anthropic.com                        NaN  2024-07-08T02:00:00+02:00
9                ey.com                        NaN  2024-04-18T02:00:00+02:00
10          openpipe.ai                        NaN  2024-03-26T01:00:00+01:00
11            canva.com                        NaN  2024-05-09T02:00:00+02:00
12         syntetica.co                        NaN  2024-07-16T02:00:00+02:00
13               zf.com                        NaN  2024-07-15T02:00:00+02:00
14        sparelabs.com                        NaN  2024-06-05T02:00:00+02:00
15            e-zinc.ca                        NaN  2024-06-27T02:00:00+02:00
16  biointelligence.com                        NaN  2024-04-25T02:00:00+02:00
17  claritisoftware.com                        NaN  2024-04-10T02:00:00+02:00
18          heylist.com  2024-06-20T02:00:00+02:00  2024-06-18T02:00:00+02:00
19           qohash.com  2024-04-24T02:00:00+02:00  2024-04-24T02:00:00+02:00
20        topicflow.com                        NaN  2024-06-25T02:00:00+02:00
21  claritisoftware.com  2024-06-26T02:00:00+02:00  2024-06-26T02:00:00+02:00
22  biointelligence.com                        NaN  2024-04-30T02:00:00+02:00
23            gaiia.com  2024-06-27T02:00:00+02:00  2024-06-27T02:00:00+02:00
24       sinnstudio.com                        NaN  2024-05-22T02:00:00+02:00
25        topicflow.com                        NaN  2024-06-25T02:00:00+02:00

   Financing Type Financing Type Normalized                     Categories  \
0             NaN                       NaN                             []
1             NaN                       NaN                             []
2             NaN                       NaN             ["private_equity"]
3             NaN                       NaN                             []
4             NaN                       NaN                             []
5        Series B                  series_b        ["series_b", "venture"]
6             NaN                       NaN             ["debt_financing"]
7        Series I                  series_i        ["series_i", "venture"]
8             NaN                       NaN                             []
9             NaN                       NaN                             []
10           Seed                      seed            ["seed", "venture"]
11            NaN                       NaN                             []
12           Seed                      seed            ["seed", "venture"]
13            NaN                       NaN                             []
14            NaN                       NaN                             []
15      Series A2                 series_a2       ["series_a2", "venture"]
16            NaN                       NaN                             []
17            NaN                       NaN             ["private_equity"]
18            NaN                       NaN             ["private_equity"]
19            NaN                       NaN             ["private_equity"]
20           Seed                      seed            ["seed", "venture"]
21            NaN                       NaN             ["private_equity"]
22           Seed                      seed            ["seed", "venture"]
23       Series A                  series_a        ["series_a", "venture"]
24            NaN                       NaN  ["private_equity", "venture"]
25            NaN                       NaN                             []

                                            Investors  Investors Count  \
0                                                 NaN              NaN
1   avivainvestors.com, lloydsbankinggroup.com, sa...              9.0
2                                                 NaN              NaN
3                               stackcapitalgroup.com              1.0
4                                 chevychasetrust.com              1.0
5                      alantra.com, blueearth.capital              2.0
6                                    runwaygrowth.com              1.0
7                                                 NaN              NaN
8                           damachotelsandresorts.com              1.0
9                                                 NaN              NaN
10                                                NaN              NaN
11                                        surocap.com              1.0
12                                                NaN              NaN
13                                            eib.org              1.0
14                                                NaN              NaN
15                                                NaN              NaN
16                                                NaN              NaN
17                                  vistaragrowth.com              1.0
18                                         accelia.vc              1.0
19        edc.ca, desjardinscapital.com, fondsftq.com              3.0
20                                                NaN              NaN
21                                           cibc.com              1.0
22                                                NaN              NaN
23                                          inovia.vc              1.0
24                                                NaN              NaN
25                                                NaN              NaN

               Amount  Amount Normalized  \
0               $1.9b         1900000000
1      $522.7 million          522700000
2              £41.7m           53671000
3        US$8 million            8000000
4       $1.96 million            1960000
5       $27.2 Million           27200000
6         $40 million           40000000
7        $685 million          685000000
8               $50mn           50000000
9            AU$10.7M            6865000
10       $6.7 million            6700000
11         $2 billion         2000000000
12       Û4.2 million            4581000
13       Û425 million          464695000
14               $10M           10000000
15            USD 31M           31000000
16                $5M            5000000
17  $24.6 million CAD           18139000
18              $1.6M            1600000
19      $17.4 million           17400000
20           CAD$2.5M            1823000
21        $10 million           10000000
22     $5 million CAD            3653000
23           US$13.2M           13200000
24              $2.5M            2500000
25              $2.5m            2500000

                                          Source Urls
0   https://www.tradefinanceglobal.com/posts/trafi...
1   https://realassets.ipe.com/news/aviva-among-le...
2   https://www.innovationnewsnetwork.com/zenobe-a...
3   https://www.globenewswire.com/news-release/202...
4   https://www.defenseworld.net/2024/04/11/chevy-...
5   https://www.mercomindia.com/funding-and-ma-rou...
6   https://www.prnewswire.com/news-releases/runwa...
7   https://iteuropa.com/news/large-language-model...
8   https://www.arabianbusiness.com/industries/tec...
9   https://www.biometricupdate.com/202404/ey-secu...
10  https://www.geekwire.com/2024/seattle-startup-...
11  https://www.investing.com/news/stock-market-ne...
12  https://tech.eu/2024/07/16/syntetica-raises-eu...
13  https://thebrakereport.com/eib-funds-zf-brakin...
14  https://www.finsmes.com/2024/06/spare-receives...
15  https://www.explorebit.io/article/e-Zinc%20Rai...
16  https://www.prweb.com/releases/biointelligence...
17  https://betakit.com/government-software-provid...
18  https://www.newswire.ca/news-releases/heylist-...
19  https://qohash.com/qohash-secures-17-4-million...
20  https://www.finsmes.com/2024/06/topicflow-rais...
21  https://www.marketscreener.com/quote/stock/CAN...
22  https://betakit.com/biointelligence-technologi...
23  https://financialpost.com/globe-newswire/gaiia...
24  https://www.finsmes.com/2024/05/sinn-studio-ra...
25  https://www.streetinsider.com/Accesswire/Topic...  >

- Effective date, Financial Type and Financial Type Normalized columns are mostly empty, I will resort to dropping the entire columns

In [82]:
df.drop(columns=["Effective date","Financing Type","Financing Type Normalized"], inplace=True)
df.head()

,Website Domain,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14T01:00:00+01:00,[],NaN,NaN,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31T02:00:00+02:00,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
2,zenobe.com,2024-07-24T02:00:00+02:00,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
3,canva.com,2024-05-01T02:00:00+02:00,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11T02:00:00+02:00,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...

It seems like the website domain doesn't need any cleaning

In [83]:
df["Website Domain"].isna().value_counts()

Website Domain
False    26
Name: count, dtype: int64

But there's some redundancies, website domain is unique. It should only occur in one record only, let's get rid of the duplicates

In [84]:
df["Website Domain"].duplicated().value_counts()

Website Domain
False    21
True      5
Name: count, dtype: int64

In [85]:
df[df["Website Domain"].duplicated()]

,Website Domain,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
2,zenobe.com,2024-07-24T02:00:00+02:00,"[""private_equity""]",NaN,NaN,£41.7m,53671000,https://www.innovationnewsnetwork.com/zenobe-a...
11,canva.com,2024-05-09T02:00:00+02:00,[],surocap.com,1.0,$2 billion,2000000000,https://www.investing.com/news/stock-market-ne...
21,claritisoftware.com,2024-06-26T02:00:00+02:00,"[""private_equity""]",cibc.com,1.0,$10 million,10000000,https://www.marketscreener.com/quote/stock/CAN...
22,biointelligence.com,2024-04-30T02:00:00+02:00,"[""seed"", ""venture""]",NaN,NaN,$5 million CAD,3653000,https://betakit.com/biointelligence-technologi...
25,topicflow.com,2024-06-25T02:00:00+02:00,[],NaN,NaN,$2.5m,2500000,https://www.streetinsider.com/Accesswire/Topic...

The five records are the ones that are duplicated, let's get rid of the duplicates.

In [86]:
df.drop_duplicates(subset=["Website Domain"],keep="first",inplace=True)

I removed the duplicates based on "Website Domain" column because the other columns of the duplicates website domain value doesn't match

I kept the first one because it has values for its respective columns than the duplicates

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 0 to 24
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Website Domain     21 non-null     object
 1   Found At           21 non-null     object
 2   Categories         21 non-null     object
 3   Investors          11 non-null     object
 4   Investors Count    11 non-null     float64
 5   Amount             21 non-null     object
 6   Amount Normalized  21 non-null     int64
 7   Source Urls        21 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.5+ KB

In [88]:
df.shape

(21, 8)

Our data set now has 21 rows and 8 columns

The only column that has null values now is "Investors" and "Investors Count". Let's take a look at that also.

In [89]:
df["Investors"]

0                                                   NaN
1     avivainvestors.com, lloydsbankinggroup.com, sa...
3                                 stackcapitalgroup.com
4                                   chevychasetrust.com
5                        alantra.com, blueearth.capital
6                                      runwaygrowth.com
7                                                   NaN
8                             damachotelsandresorts.com
9                                                   NaN
10                                                  NaN
12                                                  NaN
13                                              eib.org
14                                                  NaN
15                                                  NaN
16                                                  NaN
17                                    vistaragrowth.com
18                                           accelia.vc
19          edc.ca, desjardinscapital.com, fondsftq.com
20                                                  NaN
23                                            inovia.vc
24                                                  NaN
Name: Investors, dtype: object

I can simply fill the null space with "Not provided" it wouldn't significantly affect my analysis

In [90]:
df["Investors"].fillna("Not provided", inplace=True)

For the "Investors Count", I can either fill it with the mode or most logically, with 0. My justification comes from the fact that the space is left empty, it indicate that the business doesn't have any investor yet.

In [91]:
df["Investors Count"].fillna(0, inplace=True)

/tmp/ipython-input-3834434061.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Investors Count"].fillna(0, inplace=True)

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 21 entries, 0 to 24
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Website Domain     21 non-null     object
 1   Found At           21 non-null     object
 2   Categories         21 non-null     object
 3   Investors          21 non-null     object
 4   Investors Count    21 non-null     float64
 5   Amount             21 non-null     object
 6   Amount Normalized  21 non-null     int64
 7   Source Urls        21 non-null     object
dtypes: float64(1), int64(1), object(6)
memory usage: 1.5+ KB

Perfect, I have got rid of all null values, inconsistencies and redundancies.

Now, unto transformation

In [93]:
df.head()

,Website Domain,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14T01:00:00+01:00,[],Not provided,0.0,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31T02:00:00+02:00,[],"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
3,canva.com,2024-05-01T02:00:00+02:00,[],stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11T02:00:00+02:00,[],chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-24T02:00:00+02:00,"[""series_b"", ""venture""]","alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...

The first columns doesn't need to be transformed, but the "Found at" column definitely does.

In [94]:
df["Found At"].dtype

dtype('O')

In [95]:
df["Found At"][0][:10]

'2024-03-14'

The above output is the format I would want this column to have

In [96]:
df["Found At"] = df["Found At"].str.slice(0,10)

I will then change the datatype to supports data operations

In [97]:
df["Found At"] = pd.to_datetime(df["Found At"])

Perfect, now to the next column "Categories"

In [98]:
df.Categories

0                                []
1                                []
3                                []
4                                []
5           ["series_b", "venture"]
6                ["debt_financing"]
7           ["series_i", "venture"]
8                                []
9                                []
10              ["seed", "venture"]
12              ["seed", "venture"]
13                               []
14                               []
15         ["series_a2", "venture"]
16                               []
17               ["private_equity"]
18               ["private_equity"]
19               ["private_equity"]
20              ["seed", "venture"]
23          ["series_a", "venture"]
24    ["private_equity", "venture"]
Name: Categories, dtype: object

For this, I will have to perform some str manipulation also, for the empty list, I'll replace it with "Not Specified". For those that contain more than 1 item, I'll separate them with "&" and basically bring out the value for the ones that have 1 item.

In [99]:
# [] -> Not Specified
df.Categories = df.Categories.str.replace("[]", "Not Specified")

In [100]:

# 1 item
df.Categories[df.Categories != "Not Specified"] = df.Categories[df.Categories != "Not Specified"].str.slice(2,-2)

/tmp/ipython-input-3029041668.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df.Categories[df.Categories != "Not Specified"] = df.Categories[df.Categories != "Not Specified"].str.slice(2,-2)
/tmp/ipython-input-3029041668.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Categories[df.Categories != "Not Specified"] = df.Categories[df.Categories != "Not Specified"].str.slice(2,-2)

In [101]:
df.Categories

0                 Not Specified
1                 Not Specified
3                 Not Specified
4                 Not Specified
5           series_b", "venture
6                debt_financing
7           series_i", "venture
8                 Not Specified
9                 Not Specified
10              seed", "venture
12              seed", "venture
13                Not Specified
14                Not Specified
15         series_a2", "venture
16                Not Specified
17               private_equity
18               private_equity
19               private_equity
20              seed", "venture
23          series_a", "venture
24    private_equity", "venture
Name: Categories, dtype: object

Not for the last part, this will be tricky.

In [105]:
df.Categories[5].count('\", \"')

1

In [108]:
df.Categories[1].replace('\", \"', " & ")

'Not Specified'

In [110]:
df.Categories = df.Categories.str.replace('\", \"', " & ")

And!! I'm done with the "Categories" column

In [112]:
df.head()

,Website Domain,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14,Not Specified,Not provided,0.0,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31,Not Specified,"avivainvestors.com, lloydsbankinggroup.com, sa...",9.0,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
3,canva.com,2024-05-01,Not Specified,stackcapitalgroup.com,1.0,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11,Not Specified,chevychasetrust.com,1.0,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-24,series_b & venture,"alantra.com, blueearth.capital",2.0,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...

In [113]:
df.Investors[1]

'avivainvestors.com, lloydsbankinggroup.com, santander.co.uk, swip.com, cibc.com, societegenerale.com, natwest.us, rabobank.com, mufg.jp'

I will leave the "Investors" column as is it and only change the datatype of the "Investor Count to int instead of float

In [118]:
df["Investors Count"] = df["Investors Count"].astype(int)

In [119]:
df.head()

,Website Domain,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14,Not Specified,Not provided,0,$1.9b,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31,Not Specified,"avivainvestors.com, lloydsbankinggroup.com, sa...",9,$522.7 million,522700000,https://realassets.ipe.com/news/aviva-among-le...
3,canva.com,2024-05-01,Not Specified,stackcapitalgroup.com,1,US$8 million,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11,Not Specified,chevychasetrust.com,1,$1.96 million,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-24,series_b & venture,"alantra.com, blueearth.capital",2,$27.2 Million,27200000,https://www.mercomindia.com/funding-and-ma-rou...

Now, the next column might look like it doesn't require any corrections, but it does. The current format is only created for us humans to understand and process but computers find it difficult to work with them directly.

In [120]:
df.Amount

0                 $1.9b
1        $522.7 million
3          US$8 million
4         $1.96 million
5         $27.2 Million
6           $40 million
7          $685 million
8                 $50mn
9              AU$10.7M
10         $6.7 million
12         Û4.2 million
13         Û425 million
14                 $10M
15              USD 31M
16                  $5M
17    $24.6 million CAD
18                $1.6M
19        $17.4 million
20             CAD$2.5M
23             US$13.2M
24                $2.5M
Name: Amount, dtype: object

It looks very rough, I will assume that the currency used is $ only

Here's where things becomes interesting, Billions is represented using only b, while Millions has many variations, if you also noticed,the amount has some characters that shouldn't be there.

I will be using regular expression for this task, it is robust and can handle multiple string matching at once

In [121]:
import re

In [140]:
re.findall(r"\d+\.*\d*", "$1458M")

['1458']

In [143]:
re.findall(r"\D", "$1458M")

['$', 'M']

In [158]:
amounts = df.Amount.values

In [159]:
amounts = list(amounts)

In [174]:
amounts = [float(re.findall(r"\d+\.*\d*", amount)[0]) for amount in amounts]

In [169]:
txt_val = [[amt_lower.lower() for amt_lower in re.findall(r"\D", amount)] for amount in amounts]

In [175]:
multiplier = [1_000_000 if "m" in val else 1_000_000_000 for val in txt_val]

In [176]:
# Therefore, the total amount would be

Total_amounts = np.array(amounts)*np.array(multiplier)

Total_amounts

array([1.900e+09, 5.227e+08, 8.000e+06, 1.960e+06, 2.720e+07, 4.000e+07,
       6.850e+08, 5.000e+07, 1.070e+07, 6.700e+06, 4.200e+06, 4.250e+08,
       1.000e+07, 3.100e+07, 5.000e+06, 2.460e+07, 1.600e+06, 1.740e+07,
       2.500e+06, 1.320e+07, 2.500e+06])

Finally, let's replace what we already have with the final one

In [179]:
df.Amount = Total_amounts

In [182]:
df.head()

,Website Domain,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14,Not Specified,Not provided,0,1.900000e+09,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31,Not Specified,"avivainvestors.com, lloydsbankinggroup.com, sa...",9,5.227000e+08,522700000,https://realassets.ipe.com/news/aviva-among-le...
3,canva.com,2024-05-01,Not Specified,stackcapitalgroup.com,1,8.000000e+06,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11,Not Specified,chevychasetrust.com,1,1.960000e+06,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-24,series_b & venture,"alantra.com, blueearth.capital",2,2.720000e+07,27200000,https://www.mercomindia.com/funding-and-ma-rou...

Oh! That was already done for me, why go through all the hassle. But it's worth it.

In [187]:
df["Source Urls"].values

array(['https://www.tradefinanceglobal.com/posts/trafigura-raises-1-9b-in-new-credit-facilities-eyes-expansion',
       'https://realassets.ipe.com/news/aviva-among-lenders-backing-zenob-with-410m-of-new-debt/10073524.article, https://media.startupcentrum.com/weekly-startup-ecosystem-overview-in-europe-may-27-31',
       'https://www.globenewswire.com/news-release/2024/05/01/2873118/0/en/Stack-Capital-Invests-8-Million-USD-Into-Canva.html',
       'https://www.defenseworld.net/2024/04/11/chevy-chase-trust-holdings-llc-makes-new-1-96-million-investment-in-fidelity-msci-consumer-discretionary-index-etf-nysearcafdis.html',
       'https://www.mercomindia.com/funding-and-ma-roundup-ev-charging-swtch-raises-27-million, https://www.finsmes.com/2024/04/swtch-energy-raises-27-2m-in-series-b-funding.html',
       'https://www.prnewswire.com/news-releases/runway-growth-capital-provides-a-40-million-growth-investment-to-carnow-302117064.html, https://www.finsmes.com/2024/04/carnow-receives-40m-loan-from-runway-growth-capital.html',
       'https://iteuropa.com/news/large-language-model-walks-bar',
       'https://www.arabianbusiness.com/industries/technology/dubais-damac-group-bets-big-on-ai-with-50mn-investment-in-anthropic',
       'https://www.biometricupdate.com/202404/ey-secures-au10-7m-to-build-australia-digital-id-register-after-limited-tender',
       'https://www.geekwire.com/2024/seattle-startup-openpipe-raises-6-7m-to-help-companies-reduce-costs-for-llm-development',
       'https://tech.eu/2024/07/16/syntetica-raises-eur42m-to-close-the-loop-in-nylon-recycling',
       'https://thebrakereport.com/eib-funds-zf-braking-steering-advances',
       'https://www.finsmes.com/2024/06/spare-receives-10m-in-growth-capital.html',
       'https://www.explorebit.io/article/e-Zinc%20Raises%20USD%2031M%20Series%20A2%20Funding',
       'https://www.prweb.com/releases/biointelligence-technologies-raises-5m-to-accelerate-growth-in-america-and-europe-302125188.html',
       'https://betakit.com/government-software-provider-clariti-cloud-secures-24-6-million-cad-from-vistara-growth',
       'https://www.newswire.ca/news-releases/heylist-secures-1-6m-in-funding-to-make-influencer-marketing-accessible-801065350.html, https://finance.yahoo.com/news/heylist-secures-1-6m-funding-130000707.html',
       'https://qohash.com/qohash-secures-17-4-million-in-series-b-funding-led-by-fonds-de-solidarite-ftq-to-accelerate-growth-of-its-ai-data-security-platform, https://financialit.net/news/fundraising-news/qohash-secures-174-million-series-b-funding-led-fonds-de-solidarite-ftq, https://www.frontlines.io/jean-le-bouthillier-ceo-of-qohash/',
       'https://www.finsmes.com/2024/06/topicflow-raises-cad2-5m-in-funding.html',
       'https://financialpost.com/globe-newswire/gaiia-raises-series-a-led-by-inovia-capital-to-revolutionize-customer-experience-for-internet-service-providers, https://www.finsmes.com/2024/06/gaiia-raises-us13-2m-in-series-a-financing.html',
       'https://www.finsmes.com/2024/05/sinn-studio-raises-2-5m-in-funding.html'],
      dtype=object)

The URL column look good to me, nothing's need to be done on it.

In [184]:
df["Amount Normalized"].dtype

dtype('int64')

So my cleaning is done, my data now is ready for further analysis.

In [188]:
df

,Website Domain,Found At,Categories,Investors,Investors Count,Amount,Amount Normalized,Source Urls
0,trafigura.com,2024-03-14,Not Specified,Not provided,0,1.900000e+09,1900000000,https://www.tradefinanceglobal.com/posts/trafi...
1,zenobe.com,2024-05-31,Not Specified,"avivainvestors.com, lloydsbankinggroup.com, sa...",9,5.227000e+08,522700000,https://realassets.ipe.com/news/aviva-among-le...
3,canva.com,2024-05-01,Not Specified,stackcapitalgroup.com,1,8.000000e+06,8000000,https://www.globenewswire.com/news-release/202...
4,fidelity.com,2024-04-11,Not Specified,chevychasetrust.com,1,1.960000e+06,1960000,https://www.defenseworld.net/2024/04/11/chevy-...
5,swtchenergy.com,2024-04-24,series_b & venture,"alantra.com, blueearth.capital",2,2.720000e+07,27200000,https://www.mercomindia.com/funding-and-ma-rou...
6,carnow.com,2024-04-16,debt_financing,runwaygrowth.com,1,4.000000e+07,40000000,https://www.prnewswire.com/news-releases/runwa...
7,databricks.com,2024-08-07,series_i & venture,Not provided,0,6.850000e+08,685000000,https://iteuropa.com/news/large-language-model...
8,anthropic.com,2024-07-08,Not Specified,damachotelsandresorts.com,1,5.000000e+07,50000000,https://www.arabianbusiness.com/industries/tec...
9,ey.com,2024-04-18,Not Specified,Not provided,0,1.070000e+07,6865000,https://www.biometricupdate.com/202404/ey-secu...
10,openpipe.ai,2024-03-26,seed & venture,Not provided,0,6.700000e+06,6700000,https://www.geekwire.com/2024/seattle-startup-...
12,syntetica.co,2024-07-16,seed & venture,Not provided,0,4.200000e+06,4581000,https://tech.eu/2024/07/16/syntetica-raises-eu...
13,zf.com,2024-07-15,Not Specified,eib.org,1,4.250000e+08,464695000,https://thebrakereport.com/eib-funds-zf-brakin...
14,sparelabs.com,2024-06-05,Not Specified,Not provided,0,1.000000e+07,10000000,https://www.finsmes.com/2024/06/spare-receives...
15,e-zinc.ca,2024-06-27,series_a2 & venture,Not provided,0,3.100000e+07,31000000,https://www.explorebit.io/article/e-Zinc%20Rai...
16,biointelligence.com,2024-04-25,Not Specified,Not provided,0,5.000000e+06,5000000,https://www.prweb.com/releases/biointelligence...
17,claritisoftware.com,2024-04-10,private_equity,vistaragrowth.com,1,2.460000e+07,18139000,https://betakit.com/government-software-provid...
18,heylist.com,2024-06-18,private_equity,accelia.vc,1,1.600000e+06,1600000,https://www.newswire.ca/news-releases/heylist-...
19,qohash.com,2024-04-24,private_equity,"edc.ca, desjardinscapital.com, fondsftq.com",3,1.740000e+07,17400000,https://qohash.com/qohash-secures-17-4-million...
20,topicflow.com,2024-06-25,seed & venture,Not provided,0,2.500000e+06,1823000,https://www.finsmes.com/2024/06/topicflow-rais...
23,gaiia.com,2024-06-27,series_a & venture,inovia.vc,1,1.320000e+07,13200000,https://financialpost.com/globe-newswire/gaiia...
24,sinnstudio.com,2024-05-22,private_equity & venture,Not provided,0,2.500000e+06,2500000,https://www.finsmes.com/2024/05/sinn-studio-ra...